### ISSUE TITLE
issues after pip install xstatic (1.0.3, wheel)

### ISSUE THREAD

**Issue by ThomasWaldmann** [xstatic-py/xstatic#13]
```
tw@MacBook-Pro aaa % python3 -m venv env
tw@MacBook-Pro aaa % . env/bin/activate
(env) tw@MacBook-Pro aaa % pip install xstatic
Collecting xstatic
  Using cached XStatic-1.0.3-py3-none-any.whl.metadata (1.4 kB)
Using cached XStatic-1.0.3-py3-none-any.whl (4.4 kB)
Installing collected packages: xstatic
Successfully installed xstatic-1.0.3

# note that I am just invoking python3, not even importing xstatic myself:

(env) tw@MacBook-Pro aaa % python3
Error processing line 3 of /Users/tw/w/aaa/env/lib/python3.12/site-packages/XStatic-1.0.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 195, in addpackage
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 810, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored

Error processing line 3 of /Users/tw/w/aaa/env/lib/python3.12/site-packages/XStatic-1.0.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 195, in addpackage
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 810, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored

Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
```

**Comment by ThomasWaldmann** [comment]
That .pth file with py3.10 in its name comes from the wheel:
```
tw@MacBook-Pro whl % cat XStatic-1.0.3-py3.10-nspkg.pth 
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('xstatic',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('xstatic', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('xstatic', [os.path.dirname(p)])));m = m or sys.modules.setdefault('xstatic', types.ModuleType('xstatic'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('xstatic',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('xstatic', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('xstatic', [os.path.dirname(p)])));m = m or sys.modules.setdefault('xstatic', types.ModuleType('xstatic'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('xstatic', 'pkg'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('xstatic.pkg', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('xstatic.pkg', [os.path.dirname(p)])));m = m or sys.modules.setdefault('xstatic.pkg', types.ModuleType('xstatic.pkg'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['xstatic'], 'pkg', m)
```

**Comment by ThomasWaldmann** [comment]
Same thing happens after installing the sdist (*.tgz).

In that case the .pth filename has py3.12 in it.

**Comment by ThomasWaldmann** [comment]
Ah, this issue goes away after the first `xstatic-*` package is installed (e.g. xstatic-jquery).
